{{- if .Values.scrapeConfigs.azureResourceManager.enabled }}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ .Values.scrapeConfigs.azureResourceManager.name }}
  namespace: {{ include "monitoring-stack.namespace" . }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    scrape: config
    component: azure-resourcemanager-exporter
spec:
  jobName: {{ .Values.scrapeConfigs.azureResourceManager.jobName }}
  metricsPath: {{ .Values.scrapeConfigs.azureResourceManager.metricsPath }}
  scrapeInterval: {{ .Values.scrapeConfigs.azureResourceManager.scrapeInterval }}
  scrapeTimeout: {{ .Values.scrapeConfigs.azureResourceManager.scrapeTimeout }}
  staticConfigs:
    - targets:
        - {{ .Values.scrapeConfigs.azureResourceManager.target }}
      labels:
        namespace: {{ include "monitoring-stack.namespace" . }}
        application: {{ .Values.scrapeConfigs.azureResourceManager.labels.application }}
{{- end }}
---
{{- if .Values.scrapeConfigs.azureResourceGraph.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ .Values.scrapeConfigs.azureResourceGraph.name }}
  namespace: {{ include "monitoring-stack.namespace" . }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    scrape: config
    component: azure-resourcegraph-exporter
spec:
  jobName: {{ .Values.scrapeConfigs.azureResourceGraph.jobName }}
  metricsPath: {{ .Values.scrapeConfigs.azureResourceGraph.metricsPath }}
  scrapeInterval: {{ .Values.scrapeConfigs.azureResourceGraph.scrapeInterval }}
  scrapeTimeout: {{ .Values.scrapeConfigs.azureResourceGraph.scrapeTimeout }}
  staticConfigs:
    - targets:
        - {{ .Values.scrapeConfigs.azureResourceGraph.target }}
      labels:
        namespace: {{ include "monitoring-stack.namespace" . }}
        application: {{ .Values.scrapeConfigs.azureResourceGraph.labels.application }}
{{- end }}
