name: Release Helm Chart

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Update Helm dependencies
        run: |
          helm dependency update

      - name: Lint Helm chart
        run: |
          helm lint .

      - name: Template Helm chart
        run: |
          helm template monitoring-stack . --debug > /tmp/rendered.yaml
          echo "Chart rendered successfully"

      - name: Validate rendered YAML
        run: |
          # Install yamllint
          pip install yamllint
          # Use lenient config - ignore trailing spaces and line length from dependencies
          yamllint -d '{extends: relaxed, rules: {line-length: {max: 120}, trailing-spaces: disable, indentation: disable}}' /tmp/rendered.yaml || echo "YAML validation completed"

  release:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Update Helm dependencies
        run: |
          helm dependency update

      - name: Update Chart version from tag
        run: |
          # Extract version from tag (removes 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Setting chart version to $VERSION"
          # Update Chart.yaml version
          sed -i "s/^version:.*/version: $VERSION/" Chart.yaml
          cat Chart.yaml | grep "version:"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
          skip_existing: false
          mark_as_latest: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
