name: Renovate
on:
  schedule:
    # Run every Monday at 9 AM Oslo time (UTC+1/+2)
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
